[package]
name = "gpu_chain"
version = "1.0.0"
authors = ["GPU Chain Team"]

[addresses]
gpu_chain = "_"

[dev-addresses]
gpu_chain = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]